[package]
name = "token-info"
version = "0.1.0"
edition = "2021"

[dependencies]
base64-url = "2.0.0"
clap = { version = "4.2.2", features = ["derive"] }

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
